"""Declarative registry of GoldClub / GameStar settings for jurisdiction profiling.

One ``SettingSpec`` per setting so the probe, miner, and wizard share one map.
XML walking reuses the namespace-agnostic helpers in ``slot_setup``.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

SettingKind = Literal[
    "scalar",
    "bool",
    "int_list",
    "str_list",
    "token_map",
    "button_map",
    "ini_scalar",
    "service_enabled",
]


@dataclass(frozen=True)
class SettingSpec:
    """One configurable setting that can be probed against a Goldclub-shaped tree."""

    id: str
    label: str
    group: str
    file_rel: str
    locator: str
    kind: SettingKind
    cs_pack_delivers: bool
    per_theme: bool = False
    notes: str = ""


# Groups used by the wizard matrix (display order).
SETTING_GROUPS: tuple[str, ...] = (
    "Jurisdiction",
    "Denomination",
    "UI",
    "Math",
    "SAS",
    "Ticketing",
    "Bill acceptor",
    "Hardware",
    "Dallas",
    "Identity",
    "Aurum",
    "Audio",
    "Buttons",
)


def _spec(
    setting_id: str,
    label: str,
    group: str,
    file_rel: str,
    locator: str,
    kind: SettingKind,
    *,
    cs_pack_delivers: bool = True,
    per_theme: bool = False,
    notes: str = "",
) -> SettingSpec:
    return SettingSpec(
        id=setting_id,
        label=label,
        group=group,
        file_rel=file_rel.replace("\\", "/"),
        locator=locator,
        kind=kind,
        cs_pack_delivers=cs_pack_delivers,
        per_theme=per_theme,
        notes=notes,
    )


SETTING_SPECS: tuple[SettingSpec, ...] = (
    # --- Jurisdiction / locale (mgconfig; jurisdiction_config.xml is rare) ---
    _spec(
        "locale.target_market",
        "Target market",
        "Jurisdiction",
        "slot/themes/mgconfig.xml",
        "MarketSpecific/TargetMarket",
        "scalar",
        notes="Often left as PuertoRico in Trinidad packs — consistency rule flags this.",
    ),
    _spec(
        "locale.culture_name",
        "Culture name",
        "Jurisdiction",
        "slot/themes/mgconfig.xml",
        "CultureInfoData/CultureName",
        "scalar",
    ),
    _spec(
        "locale.language",
        "Language",
        "Jurisdiction",
        "slot/themes/mgconfig.xml",
        "Language",
        "scalar",
    ),
    _spec(
        "locale.currency_name",
        "Currency name (mgconfig)",
        "Jurisdiction",
        "slot/themes/mgconfig.xml",
        "CurrencyName",
        "scalar",
    ),
    _spec(
        "locale.currency_format",
        "Currency format",
        "Jurisdiction",
        "slot/themes/mgconfig.xml",
        "CurrencyFormat",
        "scalar",
    ),
    _spec(
        "locale.currency_short_symbol",
        "Currency short symbol",
        "Jurisdiction",
        "slot/themes/mgconfig.xml",
        "CurrencyShortSymbol",
        "scalar",
    ),
    _spec(
        "locale.hw_currency_name",
        "Currency name (HardwareConfig)",
        "Jurisdiction",
        "slot/themes/HardwareConfig.xml",
        "CurrencyName",
        "scalar",
    ),
    # --- Denomination ---
    _spec(
        "denom.list",
        "Denomination list",
        "Denomination",
        "slot/themes/mgconfig.xml",
        "DenominationList",
        "int_list",
    ),
    _spec(
        "denom.credit_rate_values",
        "Credit rate values",
        "Denomination",
        "slot/themes/mgconfig.xml",
        "CreditRateValues",
        "int_list",
    ),
    _spec(
        "denom.show_selector",
        "Show denomination selector",
        "Denomination",
        "slot/themes/mgconfig.xml",
        "ShowDenominationSelector",
        "bool",
    ),
    _spec(
        "denom.display_with_currency",
        "Display denom with currency",
        "Denomination",
        "slot/themes/mgconfig.xml",
        "DisplayDenomWithCurrency",
        "bool",
    ),
    _spec(
        "denom.display_in_currency",
        "Display denom in currency",
        "Denomination",
        "slot/themes/mgconfig.xml",
        "DisplayDenomInCurrency",
        "bool",
    ),
    # --- UI / session (mgconfig; varies by country pack) ---
    _spec(
        "ui.default_bet",
        "Default bet",
        "UI",
        "slot/themes/mgconfig.xml",
        "DefaultBet",
        "scalar",
    ),
    _spec(
        "ui.show_all_lines",
        "Show all lines",
        "UI",
        "slot/themes/mgconfig.xml",
        "ShowAllLines",
        "bool",
    ),
    _spec(
        "ui.inactivity_to_selector",
        "Inactivity seconds to game selector",
        "UI",
        "slot/themes/mgconfig.xml",
        "InactivitySecondsToGameSelector",
        "scalar",
        notes="Lab often sets 0 so the selector never auto-returns.",
    ),
    _spec(
        "ui.inactivity_to_volume",
        "Inactivity seconds to initial volume",
        "UI",
        "slot/themes/mgconfig.xml",
        "InactivitySecondsToInitialVolume",
        "scalar",
    ),
    _spec(
        "ui.check_accounting_denom",
        "Check accounting denomination",
        "UI",
        "slot/themes/mgconfig.xml",
        "CheckAccountingDenom",
        "bool",
    ),
    _spec(
        "ui.cashout_button_mode",
        "Cashout button mode",
        "UI",
        "slot/themes/mgconfig.xml",
        "TransferParameters/CashoutButtonMode",
        "scalar",
        notes="Typically Ticket vs Handpay.",
    ),
    _spec(
        "ui.partial_payout",
        "Partial payout enabled",
        "UI",
        "slot/themes/mgconfig.xml",
        "TransferParameters/PartialPayoutEnabled",
        "bool",
    ),
    _spec(
        "ui.payout_celebration_limit",
        "Payout when celebration limit",
        "UI",
        "slot/themes/mgconfig.xml",
        "TransferParameters/PayoutWhenCelebrationLimit",
        "scalar",
        notes="Typically LockAndHandpay.",
    ),
    _spec(
        "ui.multicredit_transfer",
        "Multicredit transfer enabled",
        "UI",
        "slot/themes/mgconfig.xml",
        "TransferParameters/MulticreditTransferEnabled",
        "bool",
    ),
    _spec(
        "ui.currency_short_format",
        "Currency short format",
        "UI",
        "slot/themes/mgconfig.xml",
        "CurrencyShortFormat",
        "scalar",
    ),
    _spec(
        "ui.currency_amounts_with_symbol",
        "Currency amounts with symbol",
        "UI",
        "slot/themes/mgconfig.xml",
        "CurrencyAmountsWithSymbol",
        "bool",
    ),
    _spec(
        "ui.show_theoretical_rtp",
        "Show theoretical RTP",
        "UI",
        "slot/themes/mgconfig.xml",
        "ShowTheoreticalRTP",
        "bool",
    ),
    _spec(
        "ui.max_bet_with_spin",
        "Max bet with spin",
        "UI",
        "slot/themes/mgconfig.xml",
        "MaxBetWithSpin",
        "bool",
    ),
    _spec(
        "ui.gamestar_plus",
        "GameStar Plus enabled",
        "UI",
        "slot/themes/mgconfig.xml",
        "GameStarPlusEnabled",
        "bool",
    ),
    _spec(
        "ui.service_menu_button",
        "Service menu button enabled",
        "UI",
        "slot/themes/mgconfig.xml",
        "EnableServiceMenuButton",
        "bool",
    ),
    _spec(
        "ui.game_selector_menu_visible",
        "Game selector menu visible",
        "UI",
        "slot/themes/mgconfig.xml",
        "GameSelectorMenuVisible",
        "bool",
    ),
    _spec(
        "ui.release_key_unlock",
        "Release-key unlock",
        "UI",
        "slot/themes/mgconfig.xml",
        "ReleaseKeyUnlock",
        "bool",
    ),
    _spec(
        "ui.credits_number_formatting",
        "Credits with number formatting",
        "UI",
        "slot/themes/mgconfig.xml",
        "CreditsWithNumberFormatting",
        "bool",
    ),
    _spec(
        "ui.use_egm_random",
        "Use EGM random providers",
        "UI",
        "slot/themes/mgconfig.xml",
        "ServerBasedSlot/UseEgmRandomProviders",
        "bool",
    ),
    _spec(
        "ui.external_bonus_timeout",
        "Ask for external bonus timeout",
        "UI",
        "slot/themes/mgconfig.xml",
        "AskForExternalBonusTimeout",
        "scalar",
    ),
    _spec(
        "ui.allow_mute_on_release",
        "Allow mute volume on release",
        "UI",
        "slot/themes/mgconfig.xml",
        "AllowMuteVolumeOnRelease",
        "bool",
    ),
    _spec(
        "ui.dynamic_help",
        "Dynamic help enabled",
        "UI",
        "slot/themes/mgconfig.xml",
        "DynamicHelpEnabled",
        "bool",
    ),
    _spec(
        "ui.groups_enabled",
        "Game groups enabled",
        "UI",
        "slot/themes/mgconfig.xml",
        "GroupsEnabled",
        "bool",
    ),
    # --- Math (per-theme) ---
    _spec(
        "math.return_percent",
        "Current return percent",
        "Math",
        "slot/themes/*/MathSettings.xml",
        "CurrentReturnPercent",
        "scalar",
        per_theme=True,
    ),
    _spec(
        "math.allowed_return_percents",
        "Allowed return percents",
        "Math",
        "slot/themes/*/MathSettings.xml",
        "AllowedReturnPercents",
        "str_list",
        per_theme=True,
    ),
    _spec(
        "math.fixed_bet",
        "Fixed bet",
        "Math",
        "slot/themes/*/MathSettings.xml",
        "FixedBet",
        "scalar",
        per_theme=True,
    ),
    _spec(
        "math.number_of_lines",
        "Number of lines",
        "Math",
        "slot/themes/*/MathSettings.xml",
        "NumberOfLines",
        "scalar",
        per_theme=True,
    ),
    _spec(
        "math.denomination_multiplier",
        "Denomination multiplier",
        "Math",
        "slot/themes/*/MathSettings.xml",
        "DenomConfigSettings/DenominationMultiplier",
        "scalar",
        per_theme=True,
    ),
    _spec(
        "math.bet_multipliers",
        "Bet multipliers",
        "Math",
        "slot/themes/*/MathSettings.xml",
        "DenomConfigSettings/BetMultipliers",
        "int_list",
        per_theme=True,
    ),
    _spec(
        "math.denom_return_percent",
        "Denom return percent",
        "Math",
        "slot/themes/*/MathSettings.xml",
        "DenomConfigSettings/ReturnPercent",
        "scalar",
        per_theme=True,
    ),
    # --- SAS ---
    _spec(
        "sas.funds_transfer_type",
        "Funds transfer type",
        "SAS",
        "Services/aurum/config/SASControler1/SASsetupData.xml",
        "FundsTransferType",
        "scalar",
    ),
    _spec(
        "sas.lock_when_no_comms",
        "Lock game when no SAS comms",
        "SAS",
        "Services/aurum/config/SASControler1/SASsetupData.xml",
        "LockGameWhenNoComms",
        "bool",
    ),
    _spec(
        "sas.poll_rate",
        "SAS poll rate",
        "SAS",
        "Services/aurum/config/SASControler1/SASsetupData.xml",
        "PollRate",
        "scalar",
    ),
    _spec(
        "sas.partial_transfers",
        "Partial transfers allowed",
        "SAS",
        "Services/aurum/config/SASControler1/SASsetupData.xml",
        "PartialTransfersAllowed",
        "bool",
    ),
    _spec(
        "sas.validation_extensions",
        "Support validation extensions",
        "SAS",
        "Services/aurum/config/SASControler1/SASsetupData.xml",
        "SupportValidationExtensions",
        "bool",
    ),
    _spec(
        "sas.aft_txn_unique",
        "AFT transaction id must be unique",
        "SAS",
        "Services/aurum/config/SASControler1/SASsetupData.xml",
        "AftTransactionIdMustBeUnique",
        "bool",
    ),
    _spec(
        "sas.check_redeem_multiple",
        "Check redeem ticket multiple of account denom",
        "SAS",
        "Services/aurum/config/SASControler1/SASsetupData.xml",
        "CheckRedeemTicketMultipleOfAccountDenom",
        "bool",
    ),
    _spec(
        "sas.check_redeem_credit_limit",
        "Check redeem ticket exceed credit limit",
        "SAS",
        "Services/aurum/config/SASControler1/SASsetupData.xml",
        "CheckRedeemTicketExceedCreditLimit",
        "bool",
    ),
    _spec(
        "sas.legacy_bonusing",
        "Legacy bonusing enabled",
        "SAS",
        "Services/aurum/config/SASControler1/SASsetupData.xml",
        "LegacyBonusingEnabled",
        "bool",
    ),
    _spec(
        "sas.answer_only_when_connected",
        "Answer only when EGM connected",
        "SAS",
        "Services/aurum/config/SASControler1/SASsetupData.xml",
        "AnswerOnlyWhenEgmConnected",
        "bool",
    ),
    _spec(
        "sas.system_lock_mode",
        "System lock handling mode",
        "SAS",
        "Services/aurum/config/SASControler1/SASsetupData.xml",
        "SystemLockHandlingMode",
        "scalar",
    ),
    _spec(
        "sas.chirping_enabled",
        "SAS chirping enabled",
        "SAS",
        "Services/aurum/config/SASControler1/SASsetupData.xml",
        "ChirpingEnabled",
        "bool",
    ),
    _spec(
        "sas.delay_eft_gm_busy",
        "Delay EFT while GM busy",
        "SAS",
        "Services/aurum/config/SASControler1/SASsetupData.xml",
        "DelayEFTwithGMBUSY",
        "bool",
    ),
    _spec(
        "sas.funds_wat_timeout",
        "Funds on WAT account timeout",
        "SAS",
        "Services/aurum/config/SASControler1/SASsetupData.xml",
        "FundsOnWATAccountTimeOut",
        "scalar",
    ),
    _spec(
        "sas.lock_success_timer",
        "Lock-successful timer interval",
        "SAS",
        "Services/aurum/config/SASControler1/SASsetupData.xml",
        "LockSuccessfulTimerInterval",
        "scalar",
    ),
    _spec(
        "sas.repeat_transfer_times",
        "Repeat transfer times before give-up",
        "SAS",
        "Services/aurum/config/SASControler1/SASsetupData.xml",
        "RepeatRequestTransferTimesBeforeGiveUp",
        "scalar",
    ),
    _spec(
        "sas.repeat_transfer_seconds",
        "Repeat transfer after seconds",
        "SAS",
        "Services/aurum/config/SASControler1/SASsetupData.xml",
        "RepeatRequestTransferAfterSeconds",
        "scalar",
    ),
    _spec(
        "sas.must_lock_in_txn",
        "Must be locked in transaction",
        "SAS",
        "Services/aurum/config/SASControler1/SASsetupData.xml",
        "MustBeLockedInTransaction",
        "bool",
    ),
    _spec(
        "sas.resynch_after_undelivered",
        "Resynch after undelivered",
        "SAS",
        "Services/aurum/config/SASControler1/SASsetupData.xml",
        "ResynchAfterUndelivered",
        "bool",
    ),
    _spec(
        "sas.progressive_info_timeout",
        "Progressive info timeout",
        "SAS",
        "Services/aurum/config/SASControler1/SASsetupData.xml",
        "ProgressiveInfoTimeOut",
        "scalar",
    ),
    _spec(
        "sas.answer_only_when_mapped",
        "Answer only when games are mapped",
        "SAS",
        "Services/aurum/config/SASControler1/SASsetupData.xml",
        "AnswerOnlyWhenGamesAreMapped",
        "bool",
    ),
    _spec(
        "sas.progressive_monitor_url",
        "Progressive monitor URL",
        "SAS",
        "Services/aurum/config/SASControler1/SASsetupData.xml",
        "ProgressiveMonitorURL",
        "scalar",
        notes="CS packs ship a placeholder http://server : port/ProgressiveMonitor.",
    ),
    _spec(
        "sas.address",
        "SAS address",
        "SAS",
        "Services/aurum/config/SASControler1/ClientsSet.xml",
        "SASAddress",
        "scalar",
        cs_pack_delivers=False,
        notes="Often live-only; many CS leaves ship SASsetupData without ClientsSet.",
    ),
    _spec(
        "sas.aft_enabled",
        "AFT anyAftEnabled",
        "SAS",
        "Services/aurum/config/SASControler1/ClientsSet.xml",
        "AFT.anyAftEnabled",
        "bool",
        cs_pack_delivers=False,
    ),
    _spec(
        "sas.aft_in_house",
        "AFT in-house transfers enabled",
        "SAS",
        "Services/aurum/config/SASControler1/ClientsSet.xml",
        "AFT.inHouseTransfersEnabled",
        "bool",
        cs_pack_delivers=False,
    ),
    _spec(
        "sas.host_url",
        "SAS host URL",
        "SAS",
        "Services/aurum/config/SASControler1/ClientsSet.xml",
        "HostURL",
        "scalar",
        cs_pack_delivers=False,
        notes="Often live-only; Panama CS leaves typically omit ClientsSet.",
    ),
    _spec(
        "sas.port",
        "SAS host port",
        "SAS",
        "Services/aurum/config/SASControler1/ClientsSet.xml",
        "Port",
        "scalar",
        cs_pack_delivers=False,
    ),
    _spec(
        "sas.wakeup_port",
        "SAS wake-up port",
        "SAS",
        "Services/aurum/config/SASControler1/ClientsSet.xml",
        "WakeUpPort",
        "scalar",
        cs_pack_delivers=False,
    ),
    _spec(
        "sas.unique_gmid",
        "Unique GMID template",
        "SAS",
        "Services/aurum/config/SASControler1/ClientsSet.xml",
        "UniqueGMID",
        "scalar",
        cs_pack_delivers=False,
    ),
    _spec(
        "sas.aurum_egm_id",
        "Aurum EGM id template (ClientsSet)",
        "SAS",
        "Services/aurum/config/SASControler1/ClientsSet.xml",
        "AurumEgmId",
        "scalar",
        cs_pack_delivers=False,
    ),
    _spec(
        "sas.aft_debit",
        "AFT debit transfers enabled",
        "SAS",
        "Services/aurum/config/SASControler1/ClientsSet.xml",
        "AFT.debitTransfersEnabled",
        "bool",
        cs_pack_delivers=False,
    ),
    _spec(
        "sas.aft_bonus",
        "AFT bonus transfers enabled",
        "SAS",
        "Services/aurum/config/SASControler1/ClientsSet.xml",
        "AFT.bonusTransfersEnabled",
        "bool",
        cs_pack_delivers=False,
    ),
    _spec(
        "sas.aft_lock_after_transfer",
        "AFT lock after transfer request",
        "SAS",
        "Services/aurum/config/SASControler1/ClientsSet.xml",
        "AFT.lockAfterTransferRequestSupported",
        "bool",
        cs_pack_delivers=False,
    ),
    _spec(
        "sas.validation_mode",
        "Ticket validation mode",
        "SAS",
        "Services/aurum/config/SASControler1/ClientsSet.xml",
        "ValidationMode",
        "scalar",
        cs_pack_delivers=False,
    ),
    _spec(
        "sas.accounting_denom",
        "SAS accounting denomination",
        "SAS",
        "Services/aurum/config/SASControler1/ClientsSet.xml",
        "AccountingDenomination",
        "scalar",
        cs_pack_delivers=False,
    ),
    _spec(
        "sas.cashable_ticket_expiration",
        "Cashable ticket expiration days",
        "SAS",
        "Services/aurum/config/SASControler1/ClientsSet.xml",
        "ValidationCashableTicketExpiration",
        "scalar",
        cs_pack_delivers=False,
    ),
    _spec(
        "sas.aft_partial_to_host",
        "AFT transfer less than full amount to host",
        "SAS",
        "Services/aurum/config/SASControler1/ClientsSet.xml",
        "AFT.transferToHostOfLessThanFullAvailableAmountAllowed",
        "bool",
        cs_pack_delivers=False,
    ),
    _spec(
        "sas.aft_printer_receipts",
        "AFT printer available for receipts",
        "SAS",
        "Services/aurum/config/SASControler1/ClientsSet.xml",
        "AFT.printerAvailableForTransactionReceipts",
        "bool",
        cs_pack_delivers=False,
    ),
    _spec(
        "sas.aft_custom_ticket",
        "AFT custom ticket data supported",
        "SAS",
        "Services/aurum/config/SASControler1/ClientsSet.xml",
        "AFT.customTicketDataSupported",
        "bool",
        cs_pack_delivers=False,
    ),
    _spec(
        "sas.restricted_ticket_expiration",
        "Restricted ticket expiration days",
        "SAS",
        "Services/aurum/config/SASControler1/ClientsSet.xml",
        "ValidationRestrictedTicketExpiration",
        "scalar",
        cs_pack_delivers=False,
    ),
    _spec(
        "sas.cashable_ticket_title",
        "Cashable ticket title (ClientsSet)",
        "SAS",
        "Services/aurum/config/SASControler1/ClientsSet.xml",
        "ValidationCashableTicketTitle",
        "scalar",
        cs_pack_delivers=False,
    ),
    _spec(
        "sas.restricted_ticket_title",
        "Restricted ticket title (ClientsSet)",
        "SAS",
        "Services/aurum/config/SASControler1/ClientsSet.xml",
        "ValidationRestrictedTicketTitle",
        "scalar",
        cs_pack_delivers=False,
    ),
    # --- Ticketing ---
    _spec(
        "ticket.offline_enabled",
        "Offline ticket enabled",
        "Ticketing",
        "slot/themes/HardwareConfig.xml",
        "TicketPrinterSettings/OfflineEnabled",
        "bool",
    ),
    _spec(
        "ticket.redeem_enabled",
        "Ticket redeem enabled",
        "Ticketing",
        "slot/themes/HardwareConfig.xml",
        "TicketPrinterSettings/RedeemEnabled",
        "bool",
    ),
    _spec(
        "ticket.use_currency_iso",
        "Use currency ISO on tickets",
        "Ticketing",
        "slot/themes/HardwareConfig.xml",
        "TicketPrinterSettings/UseCurrencyISO",
        "bool",
    ),
    _spec(
        "ticket.print_residuals",
        "Print residuals",
        "Ticketing",
        "slot/themes/HardwareConfig.xml",
        "TicketPrinterSettings/PrintResiduals",
        "bool",
    ),
    _spec(
        "ticket.allow_noncashable",
        "Allow non-cashable print",
        "Ticketing",
        "slot/themes/HardwareConfig.xml",
        "TicketPrinterSettings/AllowNonCashablePrint",
        "bool",
    ),
    _spec(
        "ticket.printer_enabled",
        "Ticket printer enabled",
        "Ticketing",
        "slot/themes/HardwareConfig.xml",
        "TicketPrinterSettings/Enabled",
        "bool",
    ),
    _spec(
        "ticket.finance_print",
        "Finance print enabled",
        "Ticketing",
        "slot/themes/HardwareConfig.xml",
        "TicketPrinterSettings/FinancePrintEnabled",
        "bool",
    ),
    _spec(
        "ticket.lock_on_paper_low",
        "Lock on paper low",
        "Ticketing",
        "slot/themes/HardwareConfig.xml",
        "TicketPrinterSettings/LockOnPaperLow",
        "bool",
    ),
    _spec(
        "ticket.layout_noncashable",
        "Non-cashable ticket layout",
        "Ticketing",
        "slot/themes/HardwareConfig.xml",
        "TicketPrinterSettings/LayoutNoncashableTicket",
        "scalar",
    ),
    _spec(
        "ticket.layout_promo",
        "Promo ticket layout",
        "Ticketing",
        "slot/themes/HardwareConfig.xml",
        "TicketPrinterSettings/LayoutPromoTicket",
        "scalar",
    ),
    _spec(
        "ticket.layout_handpay",
        "Handpay receipt layout",
        "Ticketing",
        "slot/themes/HardwareConfig.xml",
        "TicketPrinterSettings/LayoutHandpayReceiptTicket",
        "scalar",
    ),
    _spec(
        "ticket.layout_cashable",
        "Cashable ticket layout",
        "Ticketing",
        "slot/themes/HardwareConfig.xml",
        "TicketPrinterSettings/LayoutCashableTicket",
        "scalar",
    ),
    _spec(
        "ticket.layout_jackpot",
        "Jackpot receipt layout",
        "Ticketing",
        "slot/themes/HardwareConfig.xml",
        "TicketPrinterSettings/LayoutJackpotReceiptTicket",
        "scalar",
    ),
    _spec(
        "ticket.layout_financial",
        "Financial report layout",
        "Ticketing",
        "slot/themes/HardwareConfig.xml",
        "TicketPrinterSettings/LayoutFinancialReportTicket",
        "scalar",
    ),
    _spec(
        "oticket.location",
        "Offline ticket location",
        "Ticketing",
        "bios/etc/application/slot/oticket.xml",
        "location",
        "scalar",
    ),
    _spec(
        "oticket.address1",
        "Offline ticket address 1",
        "Ticketing",
        "bios/etc/application/slot/oticket.xml",
        "address1",
        "scalar",
    ),
    _spec(
        "oticket.address2",
        "Offline ticket address 2",
        "Ticketing",
        "bios/etc/application/slot/oticket.xml",
        "address2",
        "scalar",
    ),
    _spec(
        "oticket.expire",
        "Offline ticket expire days",
        "Ticketing",
        "bios/etc/application/slot/oticket.xml",
        "expire",
        "scalar",
    ),
    _spec(
        "oticket.cashable_title",
        "Offline ticket cashable title",
        "Ticketing",
        "bios/etc/application/slot/oticket.xml",
        "cashable",
        "scalar",
    ),
    _spec(
        "oticket.promo_title",
        "Offline ticket promo title",
        "Ticketing",
        "bios/etc/application/slot/oticket.xml",
        "promo",
        "scalar",
    ),
    _spec(
        "oticket.noncash_title",
        "Offline ticket non-cash title",
        "Ticketing",
        "bios/etc/application/slot/oticket.xml",
        "noncash",
        "scalar",
    ),
    _spec(
        "oticket.ticket_no",
        "Offline ticket starting number",
        "Ticketing",
        "bios/etc/application/slot/oticket.xml",
        "ticketNo",
        "scalar",
    ),
    _spec(
        "oticket.machine",
        "Offline ticket machine number",
        "Ticketing",
        "bios/etc/application/slot/oticket.xml",
        "machine",
        "scalar",
    ),
    # --- Bill acceptor / tokens ---
    _spec(
        "bill.tokens",
        "Bill token mappings",
        "Bill acceptor",
        "slot/themes/HardwareConfig.xml",
        "BillSettings/Bills",
        "token_map",
    ),
    _spec(
        "bill.enabled",
        "Bill acceptor enabled",
        "Bill acceptor",
        "slot/themes/HardwareConfig.xml",
        "BillSettings/Enabled",
        "bool",
    ),
    _spec(
        "bill.stacker_auto_unlock",
        "Stacker installed auto-unlock",
        "Bill acceptor",
        "slot/themes/HardwareConfig.xml",
        "BillSettings/StackerInstalledAutoUnlock",
        "bool",
    ),
    _spec(
        "bill.protocol",
        "Bill acceptor protocol (MEI/JCM)",
        "Bill acceptor",
        "slot/hwdrivers/QuixantHardware.xml",
        "BillAcceptor/currentProtocol",
        "scalar",
        cs_pack_delivers=False,
        notes="Not in CS packs — live EGM or companion pack only.",
    ),
    # --- Hardware ---
    _spec(
        "hw.type",
        "Hardware type",
        "Hardware",
        "slot/themes/HardwareConfig.xml",
        "HardwareType",
        "scalar",
    ),
    _spec(
        "hw.buttons_enabled",
        "Buttons enabled",
        "Hardware",
        "slot/themes/HardwareConfig.xml",
        "ButtonsEnabled",
        "bool",
    ),
    _spec(
        "hw.led_dimming",
        "LED dimming values",
        "Hardware",
        "slot/themes/HardwareConfig.xml",
        "LightSettings/LedDimmingValues",
        "int_list",
    ),
    _spec(
        "hw.ups_enabled",
        "UPS enabled",
        "Hardware",
        "slot/themes/HardwareConfig.xml",
        "UpsSettings/Enabled",
        "bool",
    ),
    _spec(
        "hw.mechanical_counters",
        "Mechanical counters enabled",
        "Hardware",
        "slot/themes/HardwareConfig.xml",
        "MechanicalCounters/Enabled",
        "bool",
    ),
    _spec(
        "hw.mechanical_counters_ready",
        "Check mechanical counters ready",
        "Hardware",
        "slot/themes/HardwareConfig.xml",
        "MechanicalCounters/CheckMechanicalCountersReady",
        "bool",
    ),
    _spec(
        "hw.coin_enabled",
        "Coin acceptor enabled",
        "Hardware",
        "slot/themes/HardwareConfig.xml",
        "CoinSettings/Enabled",
        "bool",
    ),
    _spec(
        "hw.aes_enabled",
        "AES enabled",
        "Hardware",
        "slot/themes/HardwareConfig.xml",
        "AESEnabled",
        "bool",
    ),
    _spec(
        "hw.tower_enabled",
        "Tower lamp enabled",
        "Hardware",
        "slot/themes/HardwareConfig.xml",
        "TowerSettings/Enabled",
        "bool",
    ),
    _spec(
        "hw.tower_lamp_report_all",
        "Tower lamp report for all",
        "Hardware",
        "slot/themes/HardwareConfig.xml",
        "TowerSettings/LampReportForAll",
        "bool",
    ),
    _spec(
        "hw.switches_enabled",
        "Door switches enabled",
        "Hardware",
        "slot/themes/HardwareConfig.xml",
        "SwitchesSettings/Enabled",
        "bool",
    ),
    _spec(
        "hw.lights_enabled",
        "Button lights enabled",
        "Hardware",
        "slot/themes/HardwareConfig.xml",
        "LightSettings/Enabled",
        "bool",
    ),
    _spec(
        "hw.led_dim_value",
        "LED dim value",
        "Hardware",
        "slot/themes/HardwareConfig.xml",
        "LightSettings/LedDimValue",
        "scalar",
    ),
    _spec(
        "hw.ups_battery_warning",
        "UPS battery warning percent",
        "Hardware",
        "slot/themes/HardwareConfig.xml",
        "UpsSettings/BatteryLevelWarningSignal",
        "scalar",
    ),
    _spec(
        "hw.ups_shutdown_seconds",
        "UPS time before shutdown (s)",
        "Hardware",
        "slot/themes/HardwareConfig.xml",
        "UpsSettings/TimeBeforeShutdownInSeconds",
        "scalar",
    ),
    _spec(
        "hw.note_dispenser_enabled",
        "Note dispenser enabled",
        "Hardware",
        "slot/themes/HardwareConfig.xml",
        "NoteDispenser/Enabled",
        "bool",
    ),
    _spec(
        "hw.hopper_enabled",
        "Hopper enabled",
        "Hardware",
        "slot/themes/HardwareConfig.xml",
        "CoinSettings/HopperEnabled",
        "bool",
    ),
    _spec(
        "hw.diverter_enabled",
        "Coin diverter enabled",
        "Hardware",
        "slot/themes/HardwareConfig.xml",
        "CoinSettings/DiverterEnabled",
        "bool",
    ),
    _spec(
        "hw.set_note_denominations",
        "Set note denominations on acceptor",
        "Hardware",
        "slot/themes/HardwareConfig.xml",
        "SetNoteDenominations",
        "bool",
    ),
    # --- Dallas ---
    _spec(
        "dallas.insert_credits",
        "Dallas insert-credits values",
        "Dallas",
        "slot/themes/HardwareConfig.xml",
        "DallasKeySettings/InsertCreditsValues",
        "int_list",
    ),
    _spec(
        "dallas.key_codes",
        "Dallas key codes",
        "Dallas",
        "slot/themes/HardwareConfig.xml",
        "DallasKeySettings/Permissions",
        "str_list",
        notes="List of Code values under Permissions/DallasKey.",
    ),
    _spec(
        "dallas.igt_key_enable",
        "IGT key enable",
        "Dallas",
        "slot/themes/HardwareConfig.xml",
        "DallasKeySettings/IGTKeyEnable",
        "bool",
    ),
    _spec(
        "dallas.nfc_enable",
        "NFC key enable",
        "Dallas",
        "slot/themes/HardwareConfig.xml",
        "DallasKeySettings/NFCKeyEnable",
        "bool",
    ),
    _spec(
        "dallas.keystick_enable",
        "Key-stick enable",
        "Dallas",
        "slot/themes/HardwareConfig.xml",
        "DallasKeySettings/KeyStickEnable",
        "bool",
    ),
    _spec(
        "dallas.accounting_by_attendant",
        "Accounting by attendant",
        "Dallas",
        "slot/themes/HardwareConfig.xml",
        "DallasKeySettings/AccountingByAttendant",
        "bool",
    ),
    _spec(
        "dallas.event_log_by_attendant",
        "Event log by attendant",
        "Dallas",
        "slot/themes/HardwareConfig.xml",
        "DallasKeySettings/EventLogByAttendant",
        "bool",
    ),
    _spec(
        "dallas.use_internal_setup",
        "Use internal Dallas setup",
        "Dallas",
        "slot/themes/HardwareConfig.xml",
        "DallasKeySettings/UseInternalSetup",
        "bool",
    ),
    # --- Identity ---
    _spec(
        "id.machine_id",
        "Machine ID template",
        "Identity",
        "slot/themes/mgconfig.xml",
        "MachineID",
        "scalar",
    ),
    _spec(
        "id.network_hostname",
        "Aurum network hostname",
        "Identity",
        "Services/aurum/config/AurumSetup.xml",
        "NetworkHostName",
        "scalar",
    ),
    _spec(
        "id.aurum_currency_code",
        "Aurum currency code",
        "Identity",
        "Services/aurum/config/AurumSetup.xml",
        "CurrencyTable/CurrencyCode",
        "scalar",
    ),
    _spec(
        "id.aurum_base_units",
        "Aurum currency base units",
        "Identity",
        "Services/aurum/config/AurumSetup.xml",
        "CurrencyTable/BaseUnits",
        "scalar",
    ),
    _spec(
        "id.aurum_egm_id",
        "Aurum EGM id template",
        "Identity",
        "Services/aurum/config/AurumSetup.xml",
        "EgmId",
        "scalar",
        notes="First EgmsDevices/EgmId (GCC_ST_!!MachineName!!_01).",
    ),
    _spec(
        "id.cabinet_serial_template",
        "Cabinet serial template",
        "Identity",
        "Services/aurum/config/AurumSetup.xml",
        "CabinetSerialNumber",
        "scalar",
    ),
    _spec(
        "id.processor_currency_id",
        "Processor currency id",
        "Identity",
        "Services/aurum/config/AurumSetup.xml",
        "ProcessorConfig/CurrencyId",
        "scalar",
    ),
    _spec(
        "id.processor_locale",
        "Processor locale id",
        "Identity",
        "Services/aurum/config/AurumSetup.xml",
        "ProcessorConfig/LocaleId",
        "scalar",
        notes="CS packs leave sl_SI for every country; consistency flags that leftover.",
    ),
    _spec(
        "id.processor_base_units",
        "Processor currency base units",
        "Identity",
        "Services/aurum/config/AurumSetup.xml",
        "ProcessorConfig/CurrencyBaseUnits",
        "scalar",
    ),
    _spec(
        "id.base_units_name",
        "Aurum currency base units name",
        "Identity",
        "Services/aurum/config/AurumSetup.xml",
        "CurrencyTable/BaseUnitsName",
        "scalar",
    ),
    _spec(
        "id.egm_alias",
        "Processor EGM alias",
        "Identity",
        "Services/aurum/config/AurumSetup.xml",
        "ProcessorConfig/egmAlias",
        "scalar",
    ),
    _spec(
        "id.stop_when_no_comm",
        "Stop when no communication",
        "Identity",
        "Services/aurum/config/AurumSetup.xml",
        "CommunicationConfig/StopWhenNoCommunication",
        "bool",
        notes="First communications device. Jamaica SAS leaves are true; Trinidad OL+SAS is false.",
    ),
    _spec(
        "id.cabinet_type",
        "Cabinet type",
        "Identity",
        "Services/aurum/config/AurumSetup.xml",
        "CabinetType",
        "scalar",
        notes="e.g. SLOT_S2 / SLOT_S3.",
    ),
    _spec(
        "id.aurum_service_uri",
        "Aurum ServiceURI template",
        "Identity",
        "Services/aurum/config/AurumSetup.xml",
        "ServiceURI",
        "scalar",
    ),
    # --- Aurum configurer INI (CS packs) ---
    _spec(
        "aurum.conf_currency",
        "AurumConfigurer currency",
        "Aurum",
        "maintenance/config/configure-aurum.conf",
        "Currency",
        "ini_scalar",
        notes="Shipped Trinidad packs often leave Currency=USD here while HardwareConfig is TTD.",
    ),
    _spec(
        "aurum.conf_cabinet_type",
        "AurumConfigurer cabinet type",
        "Aurum",
        "maintenance/config/configure-aurum.conf",
        "CabinetType",
        "ini_scalar",
    ),
    _spec(
        "aurum.conf_game_name",
        "AurumConfigurer game name",
        "Aurum",
        "maintenance/config/configure-aurum.conf",
        "GameName",
        "ini_scalar",
    ),
    _spec(
        "aurum.conf_sas_ports",
        "AurumConfigurer SAS ports",
        "Aurum",
        "maintenance/config/configure-aurum.conf",
        "SasPorts",
        "ini_scalar",
    ),
    _spec(
        "aurum.conf_sas_count",
        "AurumConfigurer SAS count",
        "Aurum",
        "maintenance/config/configure-aurum.conf",
        "SasCount",
        "ini_scalar",
    ),
    _spec(
        "aurum.conf_egm_count",
        "AurumConfigurer EGM count",
        "Aurum",
        "maintenance/config/configure-aurum.conf",
        "EgmCount",
        "ini_scalar",
    ),
    _spec(
        "aurum.conf_reqtimeout",
        "AurumConfigurer request timeout",
        "Aurum",
        "maintenance/config/configure-aurum.conf",
        "reqtimeout",
        "ini_scalar",
    ),
    _spec(
        "aurum.conf_tubo",
        "AurumConfigurer Tubo flag",
        "Aurum",
        "maintenance/config/configure-aurum.conf",
        "Tubo",
        "ini_scalar",
        notes="Often empty even on OL+SAS leaves; TuboTicket service enable is aurum.svc_tubo.",
    ),
    _spec(
        "aurum.conf_skip_service_check",
        "AurumConfigurer skip service check",
        "Aurum",
        "maintenance/config/configure-aurum.conf",
        "SkipServiceCheck",
        "ini_scalar",
        notes="Shipped empty on every GameStar CS leaf mined from the lab share.",
    ),
    _spec(
        "aurum.svc_sas",
        "Aurum SAS adapter service enabled",
        "Aurum",
        "Services/aurum/AurumServicesConfig.xml",
        "GoldClub.Aurum.Adapters.SAS",
        "service_enabled",
    ),
    _spec(
        "aurum.svc_tubo",
        "Aurum Tubo ticket service enabled",
        "Aurum",
        "Services/aurum/AurumServicesConfig.xml",
        "TuboTicketValidator",
        "service_enabled",
        notes="true on OL+SAS leaves; SAS-only packs may disable it.",
    ),
    _spec(
        "aurum.svc_progressive",
        "Aurum progressive controller enabled",
        "Aurum",
        "Services/aurum/AurumServicesConfig.xml",
        "ProgressiveControler",
        "service_enabled",
    ),
    _spec(
        "aurum.svc_scripting",
        "Aurum scripting service enabled",
        "Aurum",
        "Services/aurum/AurumServicesConfig.xml",
        "ScriptingEngine",
        "service_enabled",
    ),
    # --- Audio (not in every CS leaf) ---
    _spec(
        "audio.master_volume",
        "Master volume level",
        "Audio",
        "bios/etc/application/system/soundvolume.xml",
        "MasterVolumeLevel",
        "scalar",
        cs_pack_delivers=False,
        notes="TT-00 ships this; many TRI leaves omit it.",
    ),
    # --- jurisdiction_config.xml (JAM/PR/PANC/TRI-01/TT; not TRI-00 OL+SAS) ---
    _spec(
        "locale.jur_tag",
        "Jurisdiction tag",
        "Jurisdiction",
        "slot/themes/jurisdiction_config.xml",
        "Tag",
        "scalar",
        cs_pack_delivers=False,
        notes="Present on JAM/PR/PANC/PRU/TRI-01/TT CS leaves; TRI-00 OL+SAS omits the file.",
    ),
    _spec(
        "locale.jur_currency_symbol",
        "Jurisdiction currency symbol",
        "Jurisdiction",
        "slot/themes/jurisdiction_config.xml",
        "CurrencyDisplaySettings/CurrencySymbol",
        "scalar",
        cs_pack_delivers=False,
    ),
    _spec(
        "locale.jur_currency_base_symbol",
        "Jurisdiction currency base symbol",
        "Jurisdiction",
        "slot/themes/jurisdiction_config.xml",
        "CurrencyDisplaySettings/CurrencyBaseSymbol",
        "scalar",
        cs_pack_delivers=False,
        notes="ASCII only. OneHand reads this file as ANSI; use c for cent, not ¢.",
    ),
    _spec(
        "locale.jur_long_format",
        "Jurisdiction currency long format",
        "Jurisdiction",
        "slot/themes/jurisdiction_config.xml",
        "CurrencyDisplaySettings/CurrencyDisplayFormat/CurrencyLongFormat",
        "scalar",
        cs_pack_delivers=False,
    ),
    _spec(
        "locale.jur_short_format",
        "Jurisdiction currency short format",
        "Jurisdiction",
        "slot/themes/jurisdiction_config.xml",
        "CurrencyDisplaySettings/CurrencyDisplayFormat/CurrencyShortFormat",
        "scalar",
        cs_pack_delivers=False,
    ),
    _spec(
        "locale.jur_display_decimals",
        "Jurisdiction display decimals",
        "Jurisdiction",
        "slot/themes/jurisdiction_config.xml",
        "CurrencyDisplaySettings/EnableDisplayDecimals",
        "bool",
        cs_pack_delivers=False,
        notes="Jamaica leaves are false; Panama/PR/Peru are true.",
    ),
    _spec(
        "locale.jur_thousand_separator",
        "Jurisdiction thousand separator",
        "Jurisdiction",
        "slot/themes/jurisdiction_config.xml",
        "CurrencyDisplaySettings/EnableThousandSeparator",
        "bool",
        cs_pack_delivers=False,
    ),
    _spec(
        "locale.jur_magic_wheel_limit",
        "Magic wheel money limit",
        "Jurisdiction",
        "slot/themes/jurisdiction_config.xml",
        "MagicWheelPackSettings/MoneyLimit",
        "scalar",
        cs_pack_delivers=False,
    ),
    _spec(
        "denom.jur_single_denomination",
        "Jurisdiction single denomination",
        "Denomination",
        "slot/themes/jurisdiction_config.xml",
        "DenominationDisplay/SingleDenomination",
        "scalar",
        cs_pack_delivers=False,
    ),
    # --- Buttons (not in every CS pack; TRI-00 OL+SAS omits Keyboard.xml) ---
    _spec(
        "buttons.keyboard_map",
        "Keyboard button mappings",
        "Buttons",
        "slot/hwdrivers/Keyboard.xml",
        "mapping",
        "button_map",
        cs_pack_delivers=False,
        notes="TRI-00 OL+SAS omits Keyboard.xml; JAM/PR/PANC-02/TRI-01/TT CS leaves ship it.",
    ),
)


def all_specs() -> tuple[SettingSpec, ...]:
    return SETTING_SPECS


def specs_by_id() -> dict[str, SettingSpec]:
    return {s.id: s for s in SETTING_SPECS}


def specs_for_group(group: str) -> tuple[SettingSpec, ...]:
    return tuple(s for s in SETTING_SPECS if s.group == group)


def validate_registry() -> list[str]:
    """Return registry integrity problems (empty = ok)."""
    problems: list[str] = []
    seen: set[str] = set()
    for spec in SETTING_SPECS:
        if spec.id in seen:
            problems.append(f"duplicate id: {spec.id}")
        seen.add(spec.id)
        if not spec.file_rel:
            problems.append(f"{spec.id}: empty file_rel")
        low = spec.file_rel.casefold()
        if "serialport" in low and (
            low.endswith("layout.json") or low.endswith("locations.json")
        ):
            problems.append(f"{spec.id}: forbidden serialport map")
        if "/licen" in f"/{low}/" or low.endswith("licence.dll"):
            problems.append(f"{spec.id}: forbidden licence path")
        if spec.kind not in (
            "scalar",
            "bool",
            "int_list",
            "str_list",
            "token_map",
            "button_map",
            "ini_scalar",
            "service_enabled",
        ):
            problems.append(f"{spec.id}: bad kind {spec.kind!r}")
        if spec.per_theme and "*" not in spec.file_rel:
            problems.append(f"{spec.id}: per_theme but file_rel has no *")
    return problems
